# Generated by Django 4.2.3 on 2024-11-26 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('profile_image', models.ImageField(default=None, null=True, upload_to='profile_images/')),
                ('full_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('address', models.CharField(default=None, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=16, null=True)),
                ('institution', models.CharField(default=None, max_length=100, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_interest', models.CharField(choices=[('information technology', 'Information Technology (IT)'), ('engineering, math, and physics', 'Engineering, Math, and Physics'), ('law and justice', 'Law and Justice'), ('history and cultural studies', 'History and Cultural Studies'), ('sport and physical education', 'Sport and Physical Education'), ('social and international studies', 'Social and International Studies'), ('health, medicine, and biological sciences', 'Health, Medicine, and Biological Sciences'), ('environmental studies and sustainability', 'Environmental Studies and Sustainability')], default=None, max_length=50, null=True)),
                ('social_link', models.URLField(default=None, null=True)),
                ('profession', models.CharField(default=None, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_experience', models.IntegerField()),
                ('full_time', models.BooleanField(default=True)),
                ('total_learners', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
