# Generated by Django 4.2.3 on 2024-10-28 05:52

from django.db import migrations

from ..views import calculate_grade


def backfill_submission_grade(apps, schema_editor):
    """
    backfill_submission_grade is a data migration function that calculates the grade for each submission in the database
    and updates the grade field for each submission with the calculated grade.

    Args:
        apps (Apps): The app registry for the database schema.
        schema_editor (SchemaEditor): The schema editor for the database schema.
    """
    Submission = apps.get_model("onlinecourse", "Submission")
    submissions = Submission.objects.all()

    for submission in submissions:
        lesson = submission.lesson
        questions = lesson.questions.all().order_by("?")
        choices = submission.choices.all()

        if lesson:
            submission.grade, _ = calculate_grade(questions=questions, choices=choices)
            submission.save()

    print(f"Backfilled {len(submissions)} submissions.")


class Migration(migrations.Migration):
    dependencies = [
        ("onlinecourse", "0002_submission_grade"),
    ]

    operations = [migrations.RunPython(backfill_submission_grade)]
